# Generated by Django 3.2 on 2021-04-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answear',
            old_name='answer',
            new_name='answear',
        ),
        migrations.AlterField(
            model_name='answear',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answear', to='quiz.question', verbose_name='Question'),
        ),
    ]
